### ISSUE TITLE
does not return credentials

### ISSUE THREAD

**Issue by hellsingdeath** [ExilasP/InstaPhisher#1]
I follow all the steps but at the time of sending the link I get in the console that the link has been opened but the credentials do not reach the logs.txt file, what could it be?

**Comment by ExilasP** [comment]
Which OS do you use?

**Comment by ExilasP** [comment]
Ok I found the problem: I forgot the strlen function in the condition of the login.php file. I updated the files. Try again and tell me if your problem is solved.
